version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.4.1
  - dependency-name: sass
    versions:
    - 1.32.11
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: ember-cli
    versions:
    - 3.25.3
  - dependency-name: ember-auto-import
    versions:
    - 1.11.2
